name: Call Test Reusable Matrix Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: thenickstrick/reusable-workflows/.github/workflows/test-reusable-matrix-workflow.yml@main