name: Call Test Reusable Matrix Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: thenickstrick/reusable-workflows/.github/workflows/matrix.yml@main
    with:
      matrix_flavor: '["staging", "production"]'
      matrix_type: '["matrix-qa", "matrix-prod"]'